### ISSUE TITLE
Sign in trigonometric function

### ISSUE THREAD

**Issue by wildsm** [gratton7/OPM#1]
https://github.com/gratton7/OPM/blob/ab5d54f24ba322d286c7b9be67391df586d4e667/problems/argtrig.m#L80

Salut friends,

From the reference
J.J. More, B.S. Garbow and K.E. Hillstrom, "Testing Unconstrained Optimization Software"
problem 26 seems to be defined with a slight sign difference

riel  = n + iel * ( 1 - ciel ) - siel;
instead of
riel  = n - iel * ( 1 - ciel ) - siel;

Which is intended? Note that this does not change the global minimizers or lower bound of f=0.

Many thanks for releasing OPM, I am finding it helpful for checking code.

**Comment by gratton7** [comment]
Many thanks, corrected !
